name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
      shell: bash

    - name: Create .env file
      run: |
        echo "${{ secrets.TLS_SECRETS }}" > .env
        echo "BASIC_AUTH=${{ secrets.BASIC_AUTH }}" >> .env
      shell: bash

    - name: Build
      run: cargo build --release

    - name: publish
      run: |
        host=events.wavey.io
        ssh-keyscan -H $host >> ~/.ssh/known_hosts || exit 1
        scp ./target/release/hyper-log root@$host:/var/opt/hyper-log-latest || exit 1
        scp ./config/hyper-log.service root@$host:/etc/systemd/system/ || exit 1
        ssh root@$host "systemctl daemon-reload && systemctl stop hyper-log && mv /var/opt/hyper-log-latest /var/opt/hyper-log && systemctl enable hyper-log && systemctl restart hyper-log" || exit 1
      shell: bash
